version: "3.9" 
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - '${PG_PORT:-5432}:${PG_PORT:-5432}'
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
  # use "host.docker.internal" as host to connect to docker postgres.
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8080:80"
    depends_on:
      - postgres
  # use http://127.0.0.1:9001 to access the admin
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minio}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-minio-password}
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}